workspace:
  base: /go
  path: src/k8s.io/autoscaler
pipeline:
  build_binary:
    image: golang:1.12.1
    commands:
      - cd cluster-autoscaler
      - GOOS=linux go build -o cluster-autoscaler
    when:
      branch: cluster-autoscaler-release-1.15-getyourguide
  docker_cluster_autoscaler:
    image: hub.gyg.io/drone-plugins/gyg-registry
    privileged: true
    context: cluster-autoscaler
    dockerfile: cluster-autoscaler/Dockerfile
    repo: hub.gyg.io/devops/cluster-autoscaler
    tags:
      - v1.15.0-getyourguide
      - v${DRONE_BUILD_NUMBER}
    when:
      branch: cluster-autoscaler-release-1.15-getyourguide
